name: run-tests

on: [push, pull_request]

jobs:
    run-tests:
        name: run-tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: run test suite
              run: npm install && npm run test
